### ISSUE TITLE
Test 804 requires 401, should allow 403

### ISSUE THREAD

**Issue by cweiske** [aaronpk/micropub.rocks#48]
Test "804: Rejects unauthorized access tokens" requires

> ✖ Returned HTTP 401
> ✖ Returned a correct error response (error: insufficient_scope)

My endpoint returns 403 forbidden, and this is ok. The access token you send is not known, so there is no way to determine the scope of the token. Thus 403 is better than 401.

**Comment by aaronpk** [comment]
The test is actually very specific, read the intro paragraph again:

> You will first need to create an access token that should not be allowed to create posts, but is otherwise a valid access token for a user who would otherwise be allowed to post. 

I'm pretty sure HTTP 401 is the correct code in this case.
