### ISSUE TITLE
"Invalid endpoint URL: false" on test 301, multipart create w/two photos

### ISSUE THREAD

**Issue by snarfed** [aaronpk/micropub.rocks#49]
this is against endpoint 16. the request never hits my server, and the Response section shows `Invalid endpoint URL: false`.

**Comment by aaronpk** [comment]
bah thanks.

**Comment by snarfed** [comment]
holy crap. filed issue at 8:15, bug fix commit pushed 8:16. that's, um, a little inhuman. 🤖 🙏
