### ISSUE TITLE
delete tests do not mark the test as completed

### ISSUE THREAD

**Issue by bear** [aaronpk/micropub.rocks#50]
Below is the response my code is returning - i'm wondering if it's because i'm tombstoning and return a Location

```
HTTP/1.1 202 ACCEPTED
Server: nginx
Date: Wed, 19 Oct 2016 00:46:07 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 84
Connection: keep-alive
Location: https://bear.im/bearlog/2016/293/micropub-post-003813

Micropub delete successful for https://bear.im/bearlog/2016/293/micropub-post-003813
```

**Comment by sknebel** [comment]
Micropub.rocks matches the specification here, which doesn't allow 202 as a response code for deletes (or updates):

> The server **must** respond to successful delete and undelted requests with HTTP 200, 201 or 204. If the undelete operation caused the URL of the post to change, the server must respond with HTTP 201 and include the new URL in the HTTP Location header. Otherwise, the server must respond with 200 or 204, depending on whether the response body has content.
(https://www.w3.org/TR/micropub/#response-2)

**Comment by bear** [comment]
The micropub.rocks page for them shows `Returned HTTP 201 or 202` as the criteria tho

**Comment by aaronpk** [comment]
The prompt on the site sounds like a copypaste error. It was not intended that 202 should be accepted. Is there a reason you want to return 202 for a delete? Also looking at your example, I'm unclear why you're returning the post's own URL in the `Location` header. If anything, I would expect some sort of "status" URL being returned.

**Comment by bear** [comment]
the code path for delete ends up in the same spot as create and undelete to be honest - so I just inherited that return and it was working before :)

the code doesn't do anything immediately, it could be minutes before the delete actually happens

**Comment by aaronpk** [comment]
I guess it does make sense to allow 202 for any response. Right now 202 is only allowed for creates.

For now, I've updated the copy on the site to match what the code was doing: f13ec6ee297e54996c2723ff2c3144f3829bac82

**Comment by bear** [comment]
should I file an issue to get 202 allowed?

**Comment by aaronpk** [comment]
Darn, we *just* published an updated version of the spec yesterday. I will have to look in to whether it's possible to make any changes to it again without totally screwing ourselves now.

**Comment by bear** [comment]
I will change my code to return a 200 :)
