### ISSUE TITLE
Client test 403 expects "remove" property but spec requires "delete"

### ISSUE THREAD

**Issue by barryf** [aaronpk/micropub.rocks#54]
In client test "403: Remove a property" Micropublish fails because it sends a "delete" instead of "remove". [In the spec](https://www.w3.org/TR/micropub/#remove), however, it says you should use "delete". 

I would probably say "remove" is better to differentiate from a post "delete" so I would be open to changing my client if you want to update the spec to match your test.

**Comment by aaronpk** [comment]
I'm not sure how that happened, the spec has always said `delete`! Apparently I also thought that `remove` was more appropriate, but seeing as the spec has always said `delete`, now isn't a good time to change that. I guess the one good thing about `delete` is that it is more different from `replace` so the three actions are `add` `delete` `replace` which are distinctly different terms.

**Comment by aaronpk** [comment]
Fixed in 80cb9192e5d1d49c237828fe29a3dae6a44b0222
