### ISSUE TITLE
Enabling CORS

### ISSUE THREAD

**Issue by terminalpixel** [aaronpk/micropub.rocks#55]
Hey, just wondering if you'd be able to enable CORS support for the client tests.

I have my js mictopub library (https://github.com/terminalpixel/micropub) which passes all the tests when run in node but I'd like to be able to get it running on the frontend too but of course there is the CORS issue when making requests.

It is maybe a good idea for micropub.rocks to detect if the client is making a CORS request and display some sort of warning to say that not all micropub endpoints will have CORS enabled.

**Comment by aaronpk** [comment]
Let me know if I did that right! I'll add the warning later.
