### ISSUE TITLE
802 (Does not store access token property) fails correct response

### ISSUE THREAD

**Issue by sknebel** [aaronpk/micropub.rocks#66]
Test **802: Does not store access token property** gives me the following feedback
![grafik](https://cloud.githubusercontent.com/assets/1082036/25073570/b48fae7c-22e9-11e7-8dc5-400c1648cbf4.png)

**Comment by aaronpk** [comment]
interesting, why is your endpoint returning the content as html? This test creates the content as plain text, so it's expecting it to be returned as `{"content":"Testing accepting..."}`

**Comment by sknebel** [comment]
D'oh! I had a feeling I'm missing something. Bug on my part, will fix and report back.

**Comment by sknebel** [comment]
passes now, my mistake.

**Comment by sknebel** [comment]
(background: posts created using form-encoded request were stored in an old, html-only storage format. The query-support tests only use JSON for creation, so I missed this path while changing things to the new format)
