### ISSUE TITLE
801 (Accept access token in POST body) does send token in header as well

### ISSUE THREAD

**Issue by sknebel** [aaronpk/micropub.rocks#67]
Test 801 sends an `Authorization: <token>`  header as well, which allows my endpoint, which does not handle access tokens in the POST body, to pass it erroneously. 
(My endpoint is id=77, in case this helps reviewing logs)

**Comment by sknebel** [comment]
This also true-but-unexpected for 802 (Does not store access token property) – there it might ok to test that even if a client sends both the token does not get stored

**Comment by aaronpk** [comment]
Thanks, good catch!
