### ISSUE TITLE
Media endpoint without a path fails validation

### ISSUE THREAD

**Issue by srushe** [aaronpk/micropub.rocks#78]
The Media Endpoint tests seem to expect that the url *must* have a path portion, and can't just be a domain. I've just tried tests 700, 701, and 702, and all failed. The JSON returned by my micropub endpoint is:

```
{
    "media-endpoint": "https://babbas.deeden.co.uk/",
    "syndicate-to": [
        {
            "uid": "https://twitter.com/",
            "name": "Twitter"
        }
    ]
}
```

I'm happy to update the code that tests the URL to accept a pathless URL, but I figure it makes sense to confirm whether the issue lies with the validation or the Micropub spec. Should a URL with no path be valid, or should the spec be updated to state it's not valid? I assume the former?

**Comment by aaronpk** [comment]
Do you mean actually no path (`https://example.com`) or a path of `/` (`https://example.com/`)? There should be no technical problem with `https://example.com/` so if micropub.rocks is getting tripped up by that I would consider it a bug.

**Comment by srushe** [comment]
I actually meant a path of `/`. If it's a bug I'll look at putting a PR together 👍
